apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-publisher
spec:
  template:
    spec:
      containers:
        - name: data-publisher
          env:
            - name: DB_SERVER
              value: dev-dbsrv.example.com
            - name: DB_DATABASE
              value: StarWars
            - name: DB_USER
              value: JohnDoe
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jd-password
                  key: jd-password
            - name: LOG_LEVEL
              value: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-publisher-internal
spec:
  template:
    spec:
      containers:
        - name: data-publisher-internal
          env:
            - name: DB_SERVER
              value: dev-dbsrv.example.com
            - name: DB_DATABASE
              value: StarWars
            - name: DB_USER
              value: JohnDoe
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jd-password
                  key: jd-password
            - name: LOG_LEVEL
              value: error
            - name: INTERNAL
              value: 'true'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-publisher-support
spec:
  template:
    spec:
      containers:
        - name: data-publisher-support
          env:
            - name: DB_SERVER
              value: dev-dbsrv.example.com
            - name: DB_DATABASE
              value: StarWars
            - name: DB_USER
              value: JohnDoe
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jd-password
                  key: jd-password
            - name: LOG_LEVEL
              value: details
            - name: SUPPORT
              value: 'true'
