apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: data-publisher
spec:
  provider: azure
  secretObjects:
    - secretName: jd-password
      type: Opaque
      data:
        - objectName: jd-password
          key: jd-password
    - secretName: auth-ingress-htpasswd
      type: Opaque
      data:
        - objectName: auth-ingress-htpasswd
          key: auth
  parameters:
    tenantId: provide tenantId
    clientID: provide clientID
    usePodIdentity: 'false'
    keyvaultName: Test1KV
    objects: |-
      array:
              - |
                objectName: jd-password
                objectType: secret
              - |
                objectName: auth-ingress-htpasswd
                objectType: secret
